// engine/coefficientExtractor.js

const { EngineError, ErrorCode } = require("./errors");

// Try to reduce an AST subtree to a single numeric constant.
// Throws if the subtree contains a variable (used to guard division and multiply).
function evaluateConstant(node) {
    if (!node) throw new Error("null node in evaluateConstant");

    if (node.type === "Number") return node.value;

    if (node.type === "UnaryOp" && node.op === "-") {
        return -evaluateConstant(node.operand);
    }

    if (node.type === "BinaryOp") {
        const l = evaluateConstant(node.left);
        const r = evaluateConstant(node.right);
        switch (node.operator) {
            case "+":
                return l + r;
            case "-":
                return l - r;
            case "*":
                return l * r;
            case "/":
                if (r === 0) throw new EngineError(ErrorCode.DIVISION_BY_ZERO);
                return l / r;
        }
    }

    // If we get here the node is a Variable — not a constant
    throw new Error("variable encountered in constant evaluation");
}

// Main extraction function.
// Walks the AST and accumulates coefficients into `map`.
// `multiplier` carries the scaling factor from parent multiply/unary nodes.
//
// map keys:
//   "__constant"  → accumulated constant term
//   <varName>     → coefficient for that variable
function extract(node, map = {}, multiplier = 1) {
    if (!node) return map;

    switch (node.type) {
        case "Number": {
            map.__constant = (map.__constant || 0) + node.value * multiplier;
            return map;
        }

        case "Variable": {
            map[node.name] = (map[node.name] || 0) + multiplier;
            return map;
        }

        case "UnaryOp": {
            // Only unary minus is generated by our parser
            if (node.op === "-") {
                return extract(node.operand, map, -multiplier);
            }
            throw new EngineError(
                ErrorCode.INTERNAL_ERROR,
                `Unknown unary op: ${node.op}`,
            );
        }

        case "BinaryOp": {
            switch (node.operator) {
                case "+":
                    extract(node.left, map, multiplier);
                    extract(node.right, map, multiplier);
                    return map;

                case "-":
                    extract(node.left, map, multiplier);
                    extract(node.right, map, -multiplier);
                    return map;

                case "*": {
                    // For multiplication to be linear, one side must be a pure constant.
                    // We try left first, then right, then fail with non-linear error.
                    let constVal = null;
                    let varSide = null;

                    try {
                        constVal = evaluateConstant(node.left);
                        varSide = node.right;
                    } catch {
                        try {
                            constVal = evaluateConstant(node.right);
                            varSide = node.left;
                        } catch {
                            // Both sides contain variables → x * y → non-linear
                            throw new EngineError(ErrorCode.NON_LINEAR_TERM);
                        }
                    }

                    return extract(varSide, map, multiplier * constVal);
                }

                case "/": {
                    // Division by a constant is allowed — produces a scaled coefficient.
                    // Division by a variable is caught by the parser before we ever get here,
                    // but we defensively check again.
                    let denomVal;
                    try {
                        denomVal = evaluateConstant(node.right);
                    } catch {
                        // Variable in denominator — should have been caught by parser
                        const varName =
                            node.right.type === "Variable"
                                ? node.right.name
                                : "expression";
                        throw new EngineError(
                            ErrorCode.VARIABLE_IN_DENOMINATOR,
                            varName,
                        );
                    }

                    if (denomVal === 0) {
                        throw new EngineError(ErrorCode.DIVISION_BY_ZERO);
                    }

                    // Extract the numerator side scaled by 1/denominator
                    // Then validate that all resulting coefficients are integers
                    const scratchMap = {};
                    extract(node.left, scratchMap, multiplier / denomVal);

                    for (const [key, val] of Object.entries(scratchMap)) {
                        if (key !== "__constant" && !Number.isInteger(val)) {
                            // e.g. 3x / 2 → coefficient 1.5 for x → reject
                            throw new EngineError(
                                ErrorCode.FRACTIONAL_COEFFICIENT,
                                key,
                                val,
                            );
                        }
                        map[key] = (map[key] || 0) + val;
                    }

                    return map;
                }

                default:
                    throw new EngineError(
                        ErrorCode.INTERNAL_ERROR,
                        `Unknown operator: ${node.operator}`,
                    );
            }
        }

        default:
            throw new EngineError(
                ErrorCode.INTERNAL_ERROR,
                `Unknown AST node type: ${node.type}`,
            );
    }
}

module.exports = { extract, evaluateConstant };
